version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      # --- Regions ---
      S3_REGION: ${S3_REGION:-us-west-2}
      BEDROCK_REGION: ${BEDROCK_REGION:-us-west-2}
      PINECONE_REGION: ${PINECONE_REGION:-us-east-1}
      PINECONE_ENV: ${PINECONE_ENV:-aws-us-east-1}

      # --- Models ---
      EMBED_MODEL: ${EMBED_MODEL:-text-embedding-3-small}
      LLM_MODEL: ${LLM_MODEL:-openai.gpt-oss-120b-1:0}

      # --- Pinecone Index Config ---
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME:-knowledge}
      PINECONE_DIM: ${PINECONE_DIM:-1536}

      # --- Secrets (prefer ARNs or names in cloud; for local, real keys are ok) ---
      OPENAI_API_KEY_SECRET_ARN: ${OPENAI_API_KEY_SECRET_ARN:-}
      PINECONE_API_KEY_SECRET_ARN: ${PINECONE_API_KEY_SECRET_ARN:-}
      AWS_BEARER_TOKEN_BEDROCK_SECRET_ARN: ${AWS_BEARER_TOKEN_BEDROCK_SECRET_ARN:-}
      # Local-only fallback (do not use in prod):
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      PINECONE_API_KEY: ${PINECONE_API_KEY:-}

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: rag-ui
    ports:
      - "8501:8501"
    environment:
      # The UI will call the API at this URL
      RAG_SERVICE_URL: ${RAG_SERVICE_URL:-http://api:8000}
    depends_on:
      - api
